### ISSUE TITLE
Issues with the daemon and what is required for it.

### ISSUE THREAD

**Issue by PrimalDerp** [Nolshine/bitburner-scripts#1]
exactly as the title says i am having issues with the daemon

the daemon enters a ridiculously long sleep period after doing a single weaken and i dont know how to fix it

tbh i have no clue about programming and just enjoy the game so finding your scripts which still work was a god send, HOWEVER im also curious after looking through you other scripts that there are scripts that are needed along side the daemon.... do i need ALL the scripts in your list or just the daemon, grow, weaken and hack ones?

**Comment by Nolshine** [comment]
Sorry it took me literally years to get back to you. I was simply not expecting any activity on this repo. Looking at daemon it seems like you only need the grow/weak/hack scripts, but there are some issues due to how old daemon is. I think the sleep time is caused by the fact that timing functions (ns.getWeakenTime/ns.getGrowTime etc) actually return the expected time in milliseconds, where they used to return it in seconds in the past. so instead of taking a number of seconds and converting to ms, it's taking a number of ms and multiplying by 1000, which results in each wait cycle taking 3 orders of magnitude longer than it should. It would be a pretty simple fix, just remove the ` * 1000` part from any `wait_time = ...` statement.
